set up acceptance-tests and configure .travis.yml
jasson99/akshara-project pull request #1
Opened 2019-09-25 09:20 UTC by jasson99

set up acceptance test using nightwatch js and configure travis.yml to run the tests

2019-09-26 04:02 UTC, skshetry commented on .travis.yml
> +  - sleep 30
```suggestion
  - until curl -s localhost:8080; do sleep 5; done
```

Better to wait until the site is up. @jasson99 what do you think?

2019-09-26 04:42 UTC, skshetry reviewed
LGTM :+1:
Please try to find out if the repo has any opinion regarding with or without semicolon(`;`), and be consistent.

2019-09-26 04:42 UTC, skshetry commented on parijat-frontend/nightwatch.conf.js
> +
Remove extra line.
```suggestion
```

2019-09-26 04:42 UTC, skshetry commented on parijat-frontend/test/acceptance/features/search.feature
> +
```suggestion
```

2019-09-26 04:42 UTC, skshetry commented on parijat-frontend/test/acceptance/index.js
> +
```suggestion
```

2019-09-26 04:42 UTC, skshetry commented on parijat-frontend/test/acceptance/features/transliteration.feature
> +
```suggestion
```

2019-09-26 04:48 UTC, jasson99 commented
cc please review @individual-it

2019-09-26 05:19 UTC, individual-it requested changes
only small wording issue

please use pageObjects (new commit)

2019-09-26 05:19 UTC, individual-it commented on parijat-frontend/test/acceptance/stepDefinitions/searchContext.js
> +Given('the user has entered the english/nepali characters {string}', userEntersTheEnglishOrNepaliCharacters);
english/nepali does not make any difference, so I would get rid of it

need to specify where does the user enter the characters

```suggestion
Given('the user has entered the string {string} into the main search field', userEntersTheEnglishOrNepaliCharacters);
```

2019-09-26 05:19 UTC, individual-it commented on parijat-frontend/test/acceptance/stepDefinitions/searchContext.js
> +When('the user enters the english/nepali characters {string}', userEntersTheEnglishOrNepaliCharacters);
see comment above

2019-09-30 07:17 UTC, individual-it requested changes

2019-09-30 07:17 UTC, individual-it commented on parijat-frontend/package.json
> +    "test:e2e": "node_modules/cucumber/bin/cucumber-js --require test/acceptance/index.js --require test/acceptance/stepDefinitions"
try using https://github.com/kozhevnikov/cucumber-pretty for a nicer output

2019-09-30 09:12 UTC, phil-davis commented on parijat-frontend/test/acceptance/features/search.feature
> +  Scenario: user should be able to search in english characters using translated text
```suggestion
  Scenario: user should be able to search in english characters using transliterated text
```

2019-09-30 09:12 UTC, phil-davis commented on parijat-frontend/test/acceptance/features/search.feature
> +  Scenario: no search result should be displayed when the user search for invalid literature
```suggestion
  Scenario: no search result should be displayed when the user searches for invalid literature
```

2019-09-30 09:12 UTC, phil-davis commented on parijat-frontend/test/acceptance/features/search.feature
> +  Scenario: no search result should be displayed when the user search for invalid literature
```suggestion
  Scenario: no search result should be displayed when the user searches for invalid literature
```

2019-09-30 09:12 UTC, phil-davis commented on parijat-frontend/test/acceptance/features/search.feature
> +  So, I would be able to read them
```suggestion
  So I can read them
```

2019-09-30 09:12 UTC, phil-davis commented on parijat-frontend/test/acceptance/features/transliteration.feature
> +  So, I would be able to search using latin characters
```suggestion
  So I can search using latin characters
```

2019-10-01 11:11 UTC, jasson99 commented
@individual-it, @phil-davis

2019-10-04 04:52 UTC, phil-davis commented on parijat-frontend/package.json
> +    "cucumber-pretty": "^1.5.2",
Why is this added to the main dependencies section?
Can/should it be in `devDependencies`?

2019-10-04 06:32 UTC, phil-davis approved these changes

2019-10-11 03:26 UTC, merged